package com.sharan.deskcharm.charm;

public enum CharmType {
    EVIL_EYE, CROSS, INITIAL_S, HAMSA, CLOVER, CROWN, INFINITY,
    COMPASS, LOTUS, FEATHER, HEART, LIGHTNING, SUN,
    MANEKI_NEKO, GANESHA, STAR, MOON, PLANET, DIAMOND, LEAF, CUSTOM
}
